# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a28b4e959f32d2af3f2a2d210108e4ae96b232033d3054e0c1038f53d74d2978cfd19f9a82868817a78a8e0e790f0aa5206b8115266fab47ffd503e04a87e58

test:
  secret_key_base: 9a819d87a65fcbd2e230789b9fc97e36c644262d984b2174fe1f11e270cae9f445dac7b711255aa0f9e443b1f901b85d8181440bb892c3f1ba3f31879ff0c519

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
